bluetti:
  app:
    app-key: 19974C15BCCBC91B21A8BA71BF5
  server:
    sso: 'https://sso.bluettipower.com'
    gateway: 'https://gw.bluettipower.com'
  oauth:
    client-id: HomeAssistant
    client-secret: SG9tZUFzc2lzdGFudA==