# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _bluetti_ble_lib
else:
    import _bluetti_ble_lib

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)



def crypt_link(sn, server_crypy_data, data, data_len):
    return _bluetti_ble_lib.crypt_link(sn, server_crypy_data, data, data_len)

def clear_link_device():
    return _bluetti_ble_lib.clear_link_device()

def clear_linked_device(sn):
    return _bluetti_ble_lib.clear_linked_device(sn)

def is_device_key_ok(sn):
    return _bluetti_ble_lib.is_device_key_ok(sn)
class BIT_DATA(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    bit_code = property(_bluetti_ble_lib.BIT_DATA_bit_code_get, _bluetti_ble_lib.BIT_DATA_bit_code_set)
    bit_value = property(_bluetti_ble_lib.BIT_DATA_bit_value_get, _bluetti_ble_lib.BIT_DATA_bit_value_set)

    def __init__(self):
        _bluetti_ble_lib.BIT_DATA_swiginit(self, _bluetti_ble_lib.new_BIT_DATA())
    __swig_destroy__ = _bluetti_ble_lib.delete_BIT_DATA

# Register BIT_DATA in _bluetti_ble_lib:
_bluetti_ble_lib.BIT_DATA_swigregister(BIT_DATA)
class REG_DATA(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    fn_code = property(_bluetti_ble_lib.REG_DATA_fn_code_get, _bluetti_ble_lib.REG_DATA_fn_code_set)
    value_type = property(_bluetti_ble_lib.REG_DATA_value_type_get, _bluetti_ble_lib.REG_DATA_value_type_set)
    fn_value = property(_bluetti_ble_lib.REG_DATA_fn_value_get, _bluetti_ble_lib.REG_DATA_fn_value_set)
    fn_value_signed = property(_bluetti_ble_lib.REG_DATA_fn_value_signed_get, _bluetti_ble_lib.REG_DATA_fn_value_signed_set)
    fn_value_str = property(_bluetti_ble_lib.REG_DATA_fn_value_str_get, _bluetti_ble_lib.REG_DATA_fn_value_str_set)
    bit_values_len = property(_bluetti_ble_lib.REG_DATA_bit_values_len_get, _bluetti_ble_lib.REG_DATA_bit_values_len_set)
    bit_values = property(_bluetti_ble_lib.REG_DATA_bit_values_get, _bluetti_ble_lib.REG_DATA_bit_values_set)

    def __init__(self):
        _bluetti_ble_lib.REG_DATA_swiginit(self, _bluetti_ble_lib.new_REG_DATA())
    __swig_destroy__ = _bluetti_ble_lib.delete_REG_DATA

# Register REG_DATA in _bluetti_ble_lib:
_bluetti_ble_lib.REG_DATA_swigregister(REG_DATA)
class BLUETTI_PROTO_DATA(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    code = property(_bluetti_ble_lib.BLUETTI_PROTO_DATA_code_get, _bluetti_ble_lib.BLUETTI_PROTO_DATA_code_set)
    reg_data_len = property(_bluetti_ble_lib.BLUETTI_PROTO_DATA_reg_data_len_get, _bluetti_ble_lib.BLUETTI_PROTO_DATA_reg_data_len_set)
    reg_data = property(_bluetti_ble_lib.BLUETTI_PROTO_DATA_reg_data_get, _bluetti_ble_lib.BLUETTI_PROTO_DATA_reg_data_set)

    def __init__(self):
        _bluetti_ble_lib.BLUETTI_PROTO_DATA_swiginit(self, _bluetti_ble_lib.new_BLUETTI_PROTO_DATA())
    __swig_destroy__ = _bluetti_ble_lib.delete_BLUETTI_PROTO_DATA

# Register BLUETTI_PROTO_DATA in _bluetti_ble_lib:
_bluetti_ble_lib.BLUETTI_PROTO_DATA_swigregister(BLUETTI_PROTO_DATA)

def parse_bluetti_encrypt(sn, device_proto_data, device_proto_data_len, modbus_data, modbus_data_len, fn_code):
    return _bluetti_ble_lib.parse_bluetti_encrypt(sn, device_proto_data, device_proto_data_len, modbus_data, modbus_data_len, fn_code)

def free_bluetti_proto_data(proto):
    return _bluetti_ble_lib.free_bluetti_proto_data(proto)

def get_read_encrypt_cmd(sn, device_proto_data, device_proto_data_len, fn_code, slave_addr):
    return _bluetti_ble_lib.get_read_encrypt_cmd(sn, device_proto_data, device_proto_data_len, fn_code, slave_addr)

def get_write_single_encrypt_cmd(sn, device_proto_data, device_proto_data_len, fn_code, slave_addr, write_value):
    return _bluetti_ble_lib.get_write_single_encrypt_cmd(sn, device_proto_data, device_proto_data_len, fn_code, slave_addr, write_value)

